### ISSUE TITLE
Fix doc build

### ISSUE THREAD

**Issue by mfalesni** [RedHatQE/widgetastic.core#100]
Hello guys,

My personal Jenkins is still building the documentation and I'd like to remove that job from it. Can you take a look at making the build work on RTD or anywhere else?

@psav @RonnyPfannschmidt

**Comment by mfalesni** [comment]
Just for record, this is the current job:

```
pip install -U setuptools pip tox 'sphinx<1.7'
pip install -e .
sphinx-build -b html -d build/sphinx-doctrees docs build/htmldocs
```

**Comment by RonnyPfannschmidt** [comment]
@mfalesni thanks for the note, i'll take a look at migrating to RTD in the afternoon

**Comment by mfalesni** [comment]
Thanks, Ronny. I don't log in here under normal circumstances, so please notify me via other channel once this gets resolved.

**Comment by mfalesni** [comment]
❓ 😃

**Comment by quarckster** [comment]
Fixed in #116

**Comment by quarckster** [comment]
@psav, @mshriver this issue can be closed.

**Comment by mfalesni** [comment]
:relaxed:
