### ISSUE TITLE
DeprecationWarning driver.switch_to.alert instead self.selenium.switch_to_alert()

### ISSUE THREAD

**Issue by tstrych** [RedHatQE/widgetastic.core#173]
```
widgetastic/browser.py:743: DeprecationWarning: use driver.switch_to.alert instead
    return self.selenium.switch_to_alert()
```

https://github.com/RedHatQE/widgetastic.core/blob/a77e2b9b3258b338c4ea313728edd72cb328cbb8/src/widgetastic/browser.py#L743

**Comment by tstrych** [comment]
To add more info: 
I work for [SatQE](https://github.com/SatelliteQE), and our UI automation is build on widgetastic. 

I hit this warning in my test run. Not sure if this deprecation warning is really problem in widgetastic but you will definetely know more about that :)

**Comment by digitronik** [comment]
@tstrych thanks for issue. It's not problem but yup, we need to move on `switch_to.alert`.
Selenium deprecating direct calls of `alert`, `window`, `iframe`. Like `switch_to.window` for window switching we already adopted.

Need some unit test over alert functionality. I will add soon.
