### ISSUE TITLE
PyPI upload filename has to match project name

### ISSUE THREAD

**Issue by rsnyman** [RedHatQE/widgetastic.core#230]
I encountered this while attempting to release 1.0.1/1.0.2. Currently, if you build a package and upload it to PyPI via twine, you get the following error:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Start filename for 'widgetastic.core' with 'widgetastic.core'.
```

Digging into the [warehouse](https://github.com/pypi/warehouse) code, I discovered that [the legacy upload requires the filename to match the project name](https://github.com/pypi/warehouse/blob/629e54674ecbf128fe6f641dd271385f88113e25/warehouse/forklift/legacy.py#L1176).

In order to upload the release, I had to build it on my local machine, rename the files, and then upload them. We need to figure out how to get around this issue. I'm not sure why we didn't run into it before.

**Comment by LightOfHeaven1994** [comment]
@rsnyman this issue was fixed [here](https://github.com/RedHatQE/widgetastic.core/pull/229) right?

**Comment by rsnyman** [comment]
@LightOfHeaven1994 No, actually, PyPI wants the filename to be "widgetastic_core"

**Comment by RonnyPfannschmidt** [comment]
Recent tools should actually use normalized upload names

It may be helpful to switch to hyneks build-and-inspect-python-package + the most recent upload actions of pypa

**Comment by digitronik** [comment]
I think this is due to the new [PEP625](https://peps.python.org/pep-0625/). 

It's not an issue with PyPI, it asks for what package name we put initially i.e. `widgetastic.core` but
currently `hatch` building `widgetastic_core-1.0.3-py3-none-any.whl` which creates a problem.

We need to figure out a better solution.

**Comment by mshriver** [comment]
This gets us out of the blocked upload on legacy, but we can still consider setting the package name to be normalized per:
https://packaging.python.org/en/latest/specifications/name-normalization/
