### ISSUE TITLE
TableRow.__locator__ Breaks on DynamicTable Editing

### ISSUE THREAD

**Issue by mshriver** [RedHatQE/widgetastic.core#57]
In extending Table/TableRow for a DynamicTable to implement row_add and row_save, it has been found that the TableRow.\_\_locator\_\_ method is not functional for all tables in the MIQ UI.

Investigation points to the static `+1` that exists in the locator.  For some tables this is functional, for others it overshoots the index, where there are only 2 rows it looks for the 3rd.

https://github.com/RedHatQE/widgetastic.core/blob/master/src/widgetastic/widget.py#L1142

**Comment by mshriver** [comment]
Is there a 'probably not a bug' label?

After speaking with @mfalesni there are some potential workarounds for setting a flag that would force or stop 'adjustment' of the table row index, but they would be pretty hackish.

I'm going to approach MIQ UI team and see if they will standardize/improve their form tables.

**Comment by mfalesni** [comment]
@mshriver Yes there is :laughing:

**Comment by mshriver** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1485953

I've written this bug against the CloudForms appliacation, where this behavior was encountered.

I'm going to close this issue, we will hopefully not need any changes to (hacks) core widgetastic to support this.  Its very likely any potential changes would be more appropriate in the ManageIQ implementation of Widgetastic (Though its not in its own repo yet)
