### ISSUE TITLE
[BUG] partial_match not working as expected when filling vlan dropdown menu

### ISSUE THREAD

**Issue by jan-zmeskal** [RedHatQE/widgetastic.core#74]
So I have encountered this while I was calling [fill method](https://github.com/RedHatQE/widgetastic.patternfly/blob/50d2c60f2d9bf68c580dec3323eecf5e08e0faea/src/widgetastic_patternfly/__init__.py#L876) of a dropdown menu using partial_match. See the following actions taken in IPython:

http://pastebin.test.redhat.com/546345

I think this illustrates the situation quite well. Bottom line is: When I call fill method with exact string of the desired item, everything works OK. However when I use partial match with path of the desired item, it does not work.

**Comment by jan-zmeskal** [comment]
One more thing I found out: partial_match in that case does not work even when I feed it **the exact item** I am looking for

**Comment by quarckster** [comment]
@jan-zmeskal this issue is fixed in https://github.com/RedHatQE/widgetastic.patternfly/pull/40

**Comment by mfalesni** [comment]
Closing it then.
