### ISSUE TITLE
Switchable nested views based on value of another widget

### ISSUE THREAD

**Issue by mfalesni** [RedHatQE/widgetastic.core#8]
Sometimes eg. a select dropdown changes the next part of a form upon change. There is a possibility of creating a proxy that will, upon accessing itself, check the value of the reference widget and pick the correct view that was registered with the proxy.

Example:
```python
class AView(View):
    reference_widget = SomeWidget()
    
    form_remainder = ChangingViewProxy(value='reference_widget')

    @form_remainder.register('value 1')
    class ViewForValue1(View):
        w = Widget()

    @form_remainder.register('value 2')
    class ViewForValue2(View):
        w = AnotherWidget()
```

The next step of this would be fully dynamic views, but that will require more thinking about design and implementation. This, so far, requires that when you fill, you have to nest the remaining values into the form_remainder (if taking this sample's terminology). The fully dynamic form would take care of it in single level.

**Comment by mshriver** [comment]
Coverage for registering a 'default' or 'else' value against form_remainder?

**Comment by mfalesni** [comment]
@mshriver Hmm, good catch, that will also need care. I think it could generate an empty form if not specified, otherwise you can use "form_remainder.register_default" or something like that.

**Comment by izapolsk** [comment]
@mfalesni, @mshriver,

Are you ok  if such conditional views will be implemented in the following way:

```
class SomeView(View):
	master_widget = SomeWidget()

	@View.conditional(condition=master_widget.text == 'SomeValue', alias='CommonName')
	class SlaveView1(View)

	@View.conditional(condition=master_widget.text == 'AnotherValue', alias='CommonName')
	class SlaveView2(View)

	@View.conditional(condition='default', alias='CommonName')
	class SlaveView3(View)
```

**Comment by mfalesni** [comment]
The `confition=` syntax would not be as simple, it would have to be a lambda (to process the value and say bool) or a value to be compared. What would be the use for `alias=` ?

**Comment by izapolsk** [comment]
yes, syntax is likely to be slightly changed during implementation.
Alias will allow us to use one name for several views.
When I was writing this code sample I had in mind Add Infra Provider dialog.  Where second part of dialog is opened after provide type is chosen.

**Comment by mfalesni** [comment]
The solution I am thinking about and will be simplest is this one:
```python
view.fill({
  'provider_name': 'foo'
  'provider_type': 'bar',
  'provider_data': { ... },
})
```
Where provider_data will be a widget that will switch underlying views based on a condition (so the nesting is obligatory). I was also thinking about "including" some views, even conditionally, but that will be more difficult to master.

**Comment by izapolsk** [comment]
@mfalesni , could you give me few real world examples of where such switchable views can be used then ?

**Comment by mfalesni** [comment]
Control Actions let's say. Anywhere where something reveals a form different for each value ...
