### ISSUE TITLE
The `before_fill` return should modify `fill.was_changed`

### ISSUE THREAD

**Issue by mshriver** [RedHatQE/widgetastic.core#82]
I think that when a before_fill method is implemented for a view, its return value should modify `was_changed` in View.fill().

https://github.com/RedHatQE/widgetastic.core/blob/master/src/widgetastic/widget.py#L744

Should be a 1-line-ish change, and covers when a before_fill modifies the form.

For example, a view with a dropdown that modifies the remaining portion of the form. If this dropdown is filled in before_fill as a way to ensure it is always selected before the rest of the form is filled, and no other changes are made as a result, the caller's fill() returns False even though the form was modified.

Thoughts  @mfalesni?

**Comment by sshveta** [comment]
👍

**Comment by mfalesni** [comment]
Yeah, that would make sense. None for no-op, boolean for setting the was_changed.
