### ISSUE TITLE
Support relative paths

### ISSUE THREAD

**Issue by oshtaier** [RedHatQE/widgetastic.core#85]
We need to have support for relatives path in locators like:
```
class test(Widget):
    ROOT = ParametrizedLocator("{@my_custom_var}/a")
    CHILD_1 = '{}/a/span'.format(ROOT)
    CHILD_2 = '{}/button/span'.format(ROOT)
    def __init__(self, parent, my_custom_var, logger=None):
        Widget.__init__(self, parent, logger=logger)
        self.my_custom_var= my_custom_var
    def fill(self, values):
        access ROOT
        access CHILD_1
        access CHILD_2
```

**Comment by mfalesni** [comment]
I don't understand ... Just place an another widget in the widget.

**Comment by mfalesni** [comment]
If you use relative xpaths starting with `.`, it will look up the widgets in the context of ROOT.

**Comment by oshtaier** [comment]
I don't understand why should I do that. I need:
loc_1 = var1
loc_2 = loc_1 + xxxxx
How can I achieve that in scope of *one* widget

**Comment by mfalesni** [comment]
In your example, this should work:
```python
class Test(Widget):
    ROOT = ParametrizedLocator("{@my_custom_var}/a")
    CHILD_1 = ParametrizedString('{@ROOT}/a/span')
    CHILD_2 = ParametrizedString('{@ROOT}/button/span')
```

**Comment by mfalesni** [comment]
Remember the ParametrizedLocator is practically exclusively used for ROOT, in other cases you want the ParametrizedString as it is simpler to handle.

**Comment by oshtaier** [comment]
Okay, same problem. In result, I am getting:
```
'Locator(by=\\'xpath\\', locator="//div[contains(@id, \\'ms-architect\\') and contains(@id, \\'operatingsystem_ids\\')]")/div[@class=\\'ms-selection\\']//li[not(contains(@style, \\'display: none\\'))]/span[contains(.,\\'%s\\')]'
```
As you can see, in that part:
```and contains(@id, \\'operatingsystem_ids\\')]")/div[@```
we have redundant ```")``` after `ids\\')]`

I described the issue in emails and it is good to have it there, finally

**Comment by mfalesni** [comment]
Darn, you are right. I need to make it a sepcial case then.

**Comment by mfalesni** [comment]
I have a PR which I am adding small patches to, I will make one now that will recognize the ParametrizedLocator and retrieve the string from it instead of the obejct itself.

**Comment by oshtaier** [comment]
thanks
